data:
  path:  /path/to/rxn-models-for-polymerization/data/input/m2p_dataset_all_combinations.csv
  name: m2p-allCombinations
  proc_dir:  /path/to/rxn-models-for-polymerization/data/rxn-preprocessing
common:
  sequence:
  - IMPORT
  - STANDARDIZE
  - PREPROCESS
  - SPLIT
  - AUGMENT
  - TOKENIZE
  fragment_bond: TILDE
  reaction_column_name: rxn_reaction_m2p
rxn_import:
  input_file:  /path/to/rxn-models-for-polymerization/data/input/m2p_dataset_all_combinations.csv
  output_csv:  /path/to/rxn-models-for-polymerization/data/rxn-preprocessing/m2p-allCombinations.imported.csv
  data_format: CSV
  input_csv_column_name: rxn_reaction_m2p
  reaction_column_name: rxn_reaction_m2p
  fragment_bond: TILDE
  remove_atom_mapping: true
  column_for_light: null
  column_for_heat: null
standardize:
  input_file_path:  /path/to/rxn-models-for-polymerization/data/rxn-preprocessing/m2p-allCombinations.imported.csv
  annotation_file_paths: []
  discard_unannotated_metals: false
  output_file_path:  /path/to/rxn-models-for-polymerization/data/rxn-preprocessing/m2p-allCombinations.standardized.csv
  fragment_bond: TILDE
  reaction_column_name: rxn_reaction_m2p
  remove_stereo_if_not_defined_in_precursors: false
preprocess:
  input_file_path:  /path/to/rxn-models-for-polymerization/data/rxn-preprocessing/m2p-allCombinations.standardized.csv
  output_file_path:  /path/to/rxn-models-for-polymerization/data/rxn-preprocessing/m2p-allCombinations.processed.csv
  min_reactants: 2
  max_reactants: 10
  max_reactants_tokens: 300
  min_agents: 0
  max_agents: 0
  max_agents_tokens: 0
  min_products: 1
  max_products: 1
  max_products_tokens: 200
  max_absolute_formal_charge: 2
  fragment_bond: TILDE
  reaction_column_name: rxn_reaction_m2p
split:
  input_file_path:  /path/to/rxn-models-for-polymerization/data/rxn-preprocessing/m2p-allCombinations.processed.csv
  output_directory:  /path/to/rxn-models-for-polymerization/data/rxn-preprocessing
  split_ratio: 0.05
  reaction_column_name: rxn_reaction_m2p
  index_column: rxn_reaction_m2p
  hash_seed: 42
  shuffle_seed: 42
augment:
  input_file_path:  /path/to/rxn-models-for-polymerization/data/rxn-preprocessing/m2p-allCombinations.processed.train.csv
  output_file_path:  /path/to/rxn-models-for-polymerization/data/rxn-preprocessing/m2p-allCombinations.augmented.train.csv
  tokenize: true
  random_type: unrestricted
  permutations: 1
  reaction_column_name: rxn_reaction_m2p
  rxn_section_to_augment: precursors
  fragment_bond: TILDE
tokenize:
  input_output_pairs:
  - inp:  /path/to/rxn-models-for-polymerization/data/rxn-preprocessing/m2p-allCombinations.augmented.train.csv
    out:  /path/to/rxn-models-for-polymerization/data/rxn-preprocessing/m2p-allCombinations.augmented.train
    reaction_column_name: rxn_reaction_m2p
  - inp:  /path/to/rxn-models-for-polymerization/data/rxn-preprocessing/m2p-allCombinations.processed.validation.csv
    out:  /path/to/rxn-models-for-polymerization/data/rxn-preprocessing/m2p-allCombinations.processed.validation
    reaction_column_name: rxn_reaction_m2p
  - inp:  /path/to/rxn-models-for-polymerization/data/rxn-preprocessing/m2p-allCombinations.processed.test.csv
    out:  /path/to/rxn-models-for-polymerization/data/rxn-preprocessing/m2p-allCombinations.processed.test
    reaction_column_name: rxn_reaction_m2p
  reaction_column_name: rxn_reaction_m2p
