data:
  path: /Users/tte/Code/open_source/rxn4chemistry/rxn-models-for-polymerization/data/input/hta_dataset_all_combinations.csv
  name: hta-allCombinations
  proc_dir: /Users/tte/Code/open_source/rxn4chemistry/rxn-models-for-polymerization/data/rxn-preprocessing
common:
  sequence:
  - IMPORT
  - STANDARDIZE
  - PREPROCESS
  - SPLIT
  - AUGMENT
  - TOKENIZE
  fragment_bond: TILDE
  reaction_column_name: rxn_reaction_hta
rxn_import:
  input_file: /Users/tte/Code/open_source/rxn4chemistry/rxn-models-for-polymerization/data/input/hta_dataset_all_combinations.csv
  output_csv: /Users/tte/Code/open_source/rxn4chemistry/rxn-models-for-polymerization/data/rxn-preprocessing/hta-allCombinations.imported.csv
  data_format: CSV
  input_csv_column_name: rxn_reaction_hta
  reaction_column_name: rxn_reaction_hta
  fragment_bond: TILDE
  remove_atom_mapping: true
  column_for_light: null
  column_for_heat: null
standardize:
  input_file_path: /Users/tte/Code/open_source/rxn4chemistry/rxn-models-for-polymerization/data/rxn-preprocessing/hta-allCombinations.imported.csv
  annotation_file_paths: []
  discard_unannotated_metals: false
  output_file_path: /Users/tte/Code/open_source/rxn4chemistry/rxn-models-for-polymerization/data/rxn-preprocessing/hta-allCombinations.standardized.csv
  fragment_bond: TILDE
  reaction_column_name: rxn_reaction_hta
  remove_stereo_if_not_defined_in_precursors: false
preprocess:
  input_file_path: /Users/tte/Code/open_source/rxn4chemistry/rxn-models-for-polymerization/data/rxn-preprocessing/hta-allCombinations.standardized.csv
  output_file_path: /Users/tte/Code/open_source/rxn4chemistry/rxn-models-for-polymerization/data/rxn-preprocessing/hta-allCombinations.processed.csv
  min_reactants: 2
  max_reactants: 10
  max_reactants_tokens: 300
  min_agents: 0
  max_agents: 0
  max_agents_tokens: 0
  min_products: 1
  max_products: 1
  max_products_tokens: 200
  max_absolute_formal_charge: 2
  fragment_bond: TILDE
  reaction_column_name: rxn_reaction_hta
split:
  input_file_path: /Users/tte/Code/open_source/rxn4chemistry/rxn-models-for-polymerization/data/rxn-preprocessing/hta-allCombinations.processed.csv
  output_directory: /Users/tte/Code/open_source/rxn4chemistry/rxn-models-for-polymerization/data/rxn-preprocessing
  split_ratio: 0.05
  reaction_column_name: rxn_reaction_hta
  index_column: rxn_reaction_hta
  hash_seed: 42
  shuffle_seed: 42
augment:
  input_file_path: /Users/tte/Code/open_source/rxn4chemistry/rxn-models-for-polymerization/data/rxn-preprocessing/hta-allCombinations.processed.train.csv
  output_file_path: /Users/tte/Code/open_source/rxn4chemistry/rxn-models-for-polymerization/data/rxn-preprocessing/hta-allCombinations.augmented.train.csv
  tokenize: true
  random_type: unrestricted
  permutations: 1
  reaction_column_name: rxn_reaction_hta
  rxn_section_to_augment: precursors
  fragment_bond: TILDE
tokenize:
  input_output_pairs:
  - inp: /Users/tte/Code/open_source/rxn4chemistry/rxn-models-for-polymerization/data/rxn-preprocessing/hta-allCombinations.augmented.train.csv
    out: /Users/tte/Code/open_source/rxn4chemistry/rxn-models-for-polymerization/data/rxn-preprocessing/hta-allCombinations.augmented.train
    reaction_column_name: rxn_reaction_hta
  - inp: /Users/tte/Code/open_source/rxn4chemistry/rxn-models-for-polymerization/data/rxn-preprocessing/hta-allCombinations.processed.validation.csv
    out: /Users/tte/Code/open_source/rxn4chemistry/rxn-models-for-polymerization/data/rxn-preprocessing/hta-allCombinations.processed.validation
    reaction_column_name: rxn_reaction_hta
  - inp: /Users/tte/Code/open_source/rxn4chemistry/rxn-models-for-polymerization/data/rxn-preprocessing/hta-allCombinations.processed.test.csv
    out: /Users/tte/Code/open_source/rxn4chemistry/rxn-models-for-polymerization/data/rxn-preprocessing/hta-allCombinations.processed.test
    reaction_column_name: rxn_reaction_hta
  reaction_column_name: rxn_reaction_hta
